CREATE TABLE [Visitors] (
	VisitorId INT NOT NULL,
	FirstName NVARCHAR(128) NOT NULL,
	LastName NVARCHAR(128) NOT NULL,
	PhoneNumber NVARCHAR(15) NOT NULL UNIQUE,
  CONSTRAINT [PK_VISITORS] PRIMARY KEY CLUSTERED
  (
  [VisitorId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Ratings] (
	RatingId INT NOT NULL,
	SpectacleId INT NOT NULL,
	Name NVARCHAR(128) NOT NULL,
	Rating float NOT NULL,
  CONSTRAINT [PK_RATINGS] PRIMARY KEY CLUSTERED
  (
  [RatingId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Tickets] (
	TicketId INT NOT NULL,
	VisitorId INT NOT NULL,
	EventId INT NOT NULL,
	BoughtTime datetime NOT NULL,
	IsReturned BIT NOT NULL DEFAULT (0),
	Price decimal NOT NULL,
	SeatNum INT NOT NULL,
  CONSTRAINT [PK_TICKETS] PRIMARY KEY CLUSTERED
  (
  [TicketId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Actors] (
	ActorId INT NOT NULL,
	FirstName NVARCHAR(128) NOT NULL,
	LastName NVARCHAR(128) NOT NULL,
	PhoneNumber NVARCHAR(15) NOT NULL,
	JoinDate DATE NOT NULL
  CONSTRAINT [PK_ACTORS] PRIMARY KEY CLUSTERED
  (
  [ActorId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ActorsInSpectacles] (
	SpectacleId INT NOT NULL,
	ActorId INT NOT NULL,
	Fee decimal NOT NULL,
	Role NVARCHAR(128) NOT NULL
)
GO
CREATE TABLE [Spectacles] (
	SpectacleId INT NOT NULL,
	Title NVARCHAR(128) NOT NULL,
	Description NVARCHAR(1024) NOT NULL,
	DurationInMinutes INT NOT NULL,
	GenreId INT NOT NULL,
  CONSTRAINT [PK_SPECTACLES] PRIMARY KEY CLUSTERED
  (
  [SpectacleId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Events] (
	EventId INT NOT NULL,
	SpectacleId INT NOT NULL,
	Date datetime NOT NULL UNIQUE,
  CONSTRAINT [PK_EVENTS] PRIMARY KEY CLUSTERED
  (
  [EventId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Genres] (
	GenreId INT NOT NULL,
	Name NVARCHAR(128) NOT NULL UNIQUE,
  CONSTRAINT [PK_GENRES] PRIMARY KEY CLUSTERED
  (
  [GenreId] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO

ALTER TABLE [Ratings] WITH CHECK ADD CONSTRAINT [Ratings_fk0] FOREIGN KEY ([SpectacleId]) REFERENCES [Spectacles]([SpectacleId])
ON UPDATE CASCADE
GO
ALTER TABLE [Ratings] CHECK CONSTRAINT [Ratings_fk0]
GO

ALTER TABLE [Tickets] WITH CHECK ADD CONSTRAINT [Tickets_fk0] FOREIGN KEY ([VisitorId]) REFERENCES [Visitors]([VisitorId])
ON UPDATE CASCADE
GO
ALTER TABLE [Tickets] CHECK CONSTRAINT [Tickets_fk0]
GO
ALTER TABLE [Tickets] WITH CHECK ADD CONSTRAINT [Tickets_fk1] FOREIGN KEY ([EventId]) REFERENCES [Events]([EventId])
ON UPDATE CASCADE
GO
ALTER TABLE [Tickets] CHECK CONSTRAINT [Tickets_fk1]
GO


ALTER TABLE [ActorsInSpectacles] WITH CHECK ADD CONSTRAINT [ActorsInSpectacles_fk0] FOREIGN KEY ([SpectacleId]) REFERENCES [Spectacles]([SpectacleId])
ON UPDATE CASCADE
GO
ALTER TABLE [ActorsInSpectacles] CHECK CONSTRAINT [ActorsInSpectacles_fk0]
GO
ALTER TABLE [ActorsInSpectacles] WITH CHECK ADD CONSTRAINT [ActorsInSpectacles_fk1] FOREIGN KEY ([ActorId]) REFERENCES [Actors]([ActorId])
ON UPDATE CASCADE
GO
ALTER TABLE [ActorsInSpectacles] CHECK CONSTRAINT [ActorsInSpectacles_fk1]
GO

ALTER TABLE [Spectacles] WITH CHECK ADD CONSTRAINT [Spectacles_fk0] FOREIGN KEY ([GenreId]) REFERENCES [Genres]([GenreId])
ON UPDATE CASCADE
GO
ALTER TABLE [Spectacles] CHECK CONSTRAINT [Spectacles_fk0]
GO

ALTER TABLE [Events] WITH CHECK ADD CONSTRAINT [Events_fk0] FOREIGN KEY ([SpectacleId]) REFERENCES [Spectacles]([SpectacleId])
ON UPDATE CASCADE
GO
ALTER TABLE [Events] CHECK CONSTRAINT [Events_fk0]
GO

